DOC_DIR=doc
VERSION=0.0.1

WIDTH=1024
#WIDTH=800
DPI=$(shell echo '90 * $(WIDTH) / 1024' | bc)

all: documentation

clean:
	rm -rf doc/*

doc:
	mkdir ./doc

.PHONY: documentation
documentation: doc/overview.edoc doc/xmpp-amqp-gateway.png
	$(MAKE) doc
	erl -noshell \
		-eval 'edoc:application(mod_rabbitmq, ".", [])' \
		-run init stop
	sed -e 's:\(<p><i>Generated by EDoc\), .*\(</i></p>\):\1\2:' -i doc/*.html

doc/overview.edoc: src/overview.edoc.in
	$(MAKE) doc
	sed -e 's:%%VERSION%%:$(VERSION):g' < $< > $@

doc/%.png: src/%.svg
	inkscape --export-dpi=$(DPI) --export-png=$@ $<
